from __future__ import annotations

from typing import Protocol

from orod.domain.events import RunEvent
from orod.domain.models import RunRecord


class RunStore(Protocol):
    async def initialize(self) -> None: ...

    async def create_run(self, run: RunRecord) -> None: ...

    async def get_run(self, run_id: str) -> RunRecord | None: ...

    async def list_runs(self, limit: int = 50, offset: int = 0) -> list[RunRecord]: ...

    async def save_run(self, run: RunRecord) -> None: ...

    async def append_event(self, event: RunEvent) -> RunEvent: ...

    async def list_events(self, run_id: str, after: int = 0) -> list[RunEvent]: ...


class VectorStore(Protocol):
    async def upsert_advisory(self, advisory: dict[str, object]) -> bool: ...

    async def search(self, query: str, limit: int = 3) -> list[str]: ...
