"""Deterministic dependency remediation: version choice, pin rewriting and routing."""

import sys
import tomllib
from pathlib import Path

import httpx
import respx

from orod.adapters.execution.subprocess import SafeCommandRunner
from orod.adapters.repository.git import GitRepositoryAdapter
from orod.adapters.scanners.osv import OSVVulnerabilityAdapter
from orod.config import Settings
from orod.domain.dependencies import (
    is_remediable,
    plan_upgrades,
    rewrite_pyproject,
    rewrite_requirements,
)
from orod.domain.models import (
    DependencyUpgrade,
    Finding,
    FindingSource,
    PackageDependency,
    RepositorySnapshot,
    Severity,
)
from orod.graph.routing import is_actionable_finding


def advisory(
    advisory_id: str,
    fixed: list[str],
    *,
    name: str = "PyYAML",
    version: str = "5.3.1",
    source_file: str = "requirements.txt",
) -> Finding:
    return Finding(
        id=f"{name}-{advisory_id}",
        source=FindingSource.OSV,
        rule_id=advisory_id,
        severity=Severity.HIGH,
        title=advisory_id,
        message=advisory_id,
        file_path=source_file,
        dependency=PackageDependency(name=name, version=version, source_file=source_file),
        fixed_versions=fixed,
    )


UPGRADE = DependencyUpgrade(name="pyyaml", current_version="5.3.1", target_version="5.4")


def test_each_package_moves_to_the_smallest_version_clearing_every_advisory() -> None:
    upgrades = plan_upgrades(
        [
            # The pin sits in the range fixed by 2.1, so 1.5 does not clear this one.
            advisory("GHSA-a", ["1.5", "5.4.1", "2.1"], version="2.0"),
            advisory("GHSA-b", ["2.0.3"], version="2.0"),
            advisory("GHSA-c", ["1.2.0"], name="requests", version="1.0"),
        ]
    )

    assert [(item.name, item.current_version, item.target_version) for item in upgrades] == [
        ("PyYAML", "2.0", "2.1"),
        ("requests", "1.0", "1.2.0"),
    ]
    assert upgrades[0].advisory_ids == ["GHSA-a", "GHSA-b"]
    assert upgrades[0].finding_ids == ["PyYAML-GHSA-a", "PyYAML-GHSA-b"]


def test_findings_a_pin_change_cannot_resolve_are_not_remediable() -> None:
    assert is_remediable(advisory("GHSA-a", ["5.4"]))
    # No fixed release above the pin: the pin matched a later, unfixed range.
    assert not is_remediable(advisory("GHSA-a", ["1.0"]))
    assert not is_remediable(advisory("GHSA-a", []))
    # Lockfiles are generated by their tools; OROD does not edit them.
    assert not is_remediable(advisory("GHSA-a", ["5.4"], source_file="uv.lock"))
    assert not is_remediable(advisory("GHSA-a", ["5.4"], source_file="deps/requirements.txt"))
    assert not is_remediable(advisory("GHSA-a", ["5.4"], version="not-a-version"))
    assert plan_upgrades([advisory("GHSA-a", ["1.0"])]) == []


def test_only_remediable_advisories_are_selected_for_automated_fixing() -> None:
    assert is_actionable_finding(advisory("GHSA-a", ["5.4"]))
    assert not is_actionable_finding(advisory("GHSA-a", []))
    assert not is_actionable_finding(advisory("GHSA-a", ["5.4"], source_file="poetry.lock"))


def test_requirements_pins_are_rewritten_without_touching_anything_else() -> None:
    content = (
        "# PyYAML==5.3.1 stays in comments\n"
        "-r base-requirements.txt\n"
        "pyyaml == 5.3.1 ; python_version >= '3.8'\n"
        "types-PyYAML==5.3.1\n"
        "PyYAML==5.3.10\n"
        "requests==2.0\n"
        "PYYAML==5.3.1"
    )

    assert rewrite_requirements(content, [UPGRADE]) == (
        "# PyYAML==5.3.1 stays in comments\n"
        "-r base-requirements.txt\n"
        "pyyaml == 5.4 ; python_version >= '3.8'\n"
        "types-PyYAML==5.3.1\n"
        "PyYAML==5.3.10\n"
        "requests==2.0\n"
        "PYYAML==5.4"
    )


def test_pyproject_pins_are_rewritten_inside_their_strings() -> None:
    content = (
        '[project]\nname = "demo"\nversion = "5.3.1"\n'
        'dependencies = [\n  "PyYAML==5.3.1",\n  "types-pyyaml==5.3.1",\n]\n'
        "[project.optional-dependencies]\nyaml = ['pyyaml==5.3.1; os_name == \"posix\"']\n"
    )

    rewritten = rewrite_pyproject(content, [UPGRADE])

    data = tomllib.loads(rewritten)
    assert data["project"]["version"] == "5.3.1"
    assert data["project"]["dependencies"] == ["PyYAML==5.4", "types-pyyaml==5.3.1"]
    assert data["project"]["optional-dependencies"]["yaml"] == ['pyyaml==5.4; os_name == "posix"']


async def test_the_repository_renders_every_manifest_pin_as_one_diff(tmp_path: Path) -> None:
    workspace = tmp_path / "workspaces"
    repository = workspace / "repo"
    repository.mkdir(parents=True)
    (repository / "requirements.txt").write_text("PyYAML==5.3.1\nrequests==2.0\n")
    (repository / "requirements-dev.txt").write_text("pytest==8.0\npyyaml==5.3.1\n")
    (repository / "pyproject.toml").write_text('[project]\ndependencies = ["httpx==0.28"]\n')
    (repository / "uv.lock").write_text('[[package]]\nname = "pyyaml"\nversion = "5.3.1"\n')
    adapter = GitRepositoryAdapter(
        Settings(workspace_root=workspace), SafeCommandRunner({sys.executable}, workspace)
    )
    snapshot = RepositorySnapshot(repository_url="demo://repo", workspace_path=str(repository))

    diff, changed = await adapter.upgrade_dependencies(snapshot, [UPGRADE])

    assert changed == ["requirements-dev.txt", "requirements.txt"]
    assert "-pyyaml==5.3.1\n+pyyaml==5.4\n" in diff
    assert "-PyYAML==5.3.1\n+PyYAML==5.4\n" in diff
    assert "uv.lock" not in diff and "pyproject.toml" not in diff


@respx.mock
async def test_osv_findings_carry_the_dependency_and_its_fixed_versions() -> None:
    respx.post("https://api.osv.dev/v1/querybatch").mock(
        return_value=httpx.Response(200, json={"results": [{"vulns": [{"id": "GHSA-demo"}]}]})
    )
    respx.get("https://api.osv.dev/v1/vulns/GHSA-demo").mock(
        return_value=httpx.Response(
            200,
            json={
                "id": "GHSA-demo",
                "affected": [
                    {
                        "package": {"ecosystem": "PyPI", "name": "pyyaml"},
                        "ranges": [
                            {
                                "type": "ECOSYSTEM",
                                "events": [{"introduced": "0"}, {"fixed": "5.4"}],
                            },
                            {"type": "GIT", "events": [{"introduced": "0"}, {"fixed": "a1b2c3"}]},
                            {
                                "type": "ECOSYSTEM",
                                "events": [{"introduced": "6.0"}, {"fixed": "6.0.1"}],
                            },
                        ],
                    },
                    {
                        "package": {"ecosystem": "PyPI", "name": "other"},
                        "ranges": [{"type": "ECOSYSTEM", "events": [{"fixed": "9.9"}]}],
                    },
                ],
            },
        )
    )
    dependency = PackageDependency(name="PyYAML", version="5.3.1", source_file="requirements.txt")

    findings, _ = await OSVVulnerabilityAdapter().scan_dependencies([dependency])

    assert findings[0].dependency == dependency
    assert findings[0].fixed_versions == ["5.4", "6.0.1"]
    assert is_remediable(findings[0])
