from __future__ import annotations

import json
import re
from pathlib import Path

from orod.domain.errors import OrodError
from orod.domain.models import (
    PatchProposal,
    PullRequestResult,
    RepositorySnapshot,
    ValidationResult,
)
from orod.ports.execution import CommandRunner


class GitHubCLIPublisher:
    def __init__(self, runner: CommandRunner) -> None:
        self._runner = runner

    async def publish(
        self,
        snapshot: RepositorySnapshot,
        patch: PatchProposal,
        validation: ValidationResult,
        run_id: str,
    ) -> PullRequestResult:
        if not validation.passed:
            raise OrodError("refusing to publish an unvalidated patch")
        if snapshot.permission not in {"ADMIN", "MAINTAIN", "WRITE"}:
            raise OrodError("refusing to publish without GitHub write permission")

        root = Path(snapshot.workspace_path)
        branch = f"orod/security-{run_id}"
        existing = await self._runner.run(
            ["gh", "pr", "view", branch, "--json", "url,number,isDraft"], root
        )
        if existing.return_code == 0:
            payload = json.loads(existing.stdout)
            return PullRequestResult(
                url=str(payload["url"]),
                number=int(payload["number"]),
                branch=branch,
                draft=bool(payload.get("isDraft", True)),
            )

        commands = [
            ["git", "checkout", "-b", branch],
            ["git", "add", "--", *patch.changed_files],
            ["git", "commit", "-m", "fix(security): remediate automated findings"],
            ["git", "push", "-u", "origin", branch],
        ]
        for argv in commands:
            result = await self._runner.run(argv, root)
            if result.return_code != 0:
                raise OrodError(
                    self._safe_error(result.stderr or result.stdout, "Git publish failed")
                )

        body = self._pull_request_body(patch, validation, run_id)
        created = await self._runner.run(
            [
                "gh",
                "pr",
                "create",
                "--draft",
                "--base",
                snapshot.base_branch,
                "--head",
                branch,
                "--title",
                "fix(security): automated remediation",
                "--body",
                body,
            ],
            root,
        )
        if created.return_code != 0:
            raise OrodError(
                self._safe_error(created.stderr or created.stdout, "PR creation failed")
            )
        url = created.stdout.strip().splitlines()[-1]
        number_match = re.search(r"/(\d+)$", url)
        return PullRequestResult(
            url=url,
            number=int(number_match.group(1)) if number_match else None,
            branch=branch,
        )

    @staticmethod
    def _pull_request_body(patch: PatchProposal, validation: ValidationResult, run_id: str) -> str:
        return "\n".join(
            [
                "## OROD automated security remediation",
                "",
                patch.explanation,
                "",
                f"- Run ID: `{run_id}`",
                f"- Findings addressed: {len(patch.finding_ids)}",
                f"- Files changed: {', '.join(f'`{path}`' for path in patch.changed_files)}",
                f"- Validation: {validation.summary}",
                "",
                "> This draft pull request was generated by an AI-assisted security workflow.",
                "> Review all changes before marking it ready or merging.",
            ]
        )

    @staticmethod
    def _safe_error(text: str, fallback: str) -> str:
        lines = text.strip().splitlines()
        return lines[-1][:500] if lines else fallback
